# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
arr0 = np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
arr5 = arr1 * 5
arr5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
arr_int = np.array([*range(10,51)])
arr_int

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
arr_even = np.array([x for x in range(10,51) if x%2 == 0])
arr_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
arr_matrix = np.array([*range(9)])
arr_3matrix = arr_matrix.reshape(3,3)
arr_3matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [26]:
arr_identity = np.identity(3)
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [33]:
random_number = np.random.rand()
random_number

0.7492142071938288

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [35]:
random_array = np.random.normal(size=(1, 25))
random_array

array([[-0.9220407 ,  0.73428656,  0.82546643,  0.66630651, -1.96032609,
        -1.2364856 , -0.34219178, -0.28321858,  1.38051648, -0.46953569,
         2.13223341, -0.78245342,  0.785744  ,  0.86590573,  0.45938803,
        -1.17800018, -1.66270518,  1.81243753, -0.72668289, -0.56923007,
         0.27879048, -0.89338179, -0.01188522, -0.63611329, -0.45025384]])

#### Create the following matrix:

In [43]:
x = np.random.uniform(size=(10, 10))
new_x = np.around(x,2)
new_x

array([[0.58, 0.65, 0.32, 0.34, 0.41, 0.18, 0.15, 0.67, 0.19, 0.67],
       [0.83, 0.71, 0.27, 0.88, 0.93, 0.21, 0.28, 0.22, 0.85, 0.93],
       [0.69, 0.68, 0.12, 0.63, 0.12, 0.17, 0.82, 0.72, 0.92, 0.45],
       [0.85, 0.65, 0.97, 0.93, 0.38, 0.03, 0.34, 0.55, 0.27, 0.15],
       [0.66, 0.55, 0.05, 0.86, 0.26, 0.7 , 0.87, 0.1 , 0.19, 0.21],
       [0.42, 0.24, 0.42, 0.06, 0.9 , 0.79, 0.34, 0.23, 0.67, 0.26],
       [0.93, 0.41, 0.85, 0.27, 0.38, 0.2 , 0.05, 0.83, 0.61, 0.48],
       [0.23, 0.17, 0.99, 0.29, 0.87, 0.52, 0.67, 0.36, 0.71, 0.82],
       [0.03, 0.45, 0.85, 0.85, 0.39, 0.55, 0.15, 0.95, 0.58, 0.17],
       [0.65, 0.88, 0.76, 0.84, 0.04, 0.14, 0.03, 0.67, 0.74, 0.74]])

In [57]:
a = np.arange(0.01,1.01,0.01).reshape(10,10)
a

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [45]:
array_20 = x = np.random.uniform(size=(1, 20))
array_20

array([[0.80068995, 0.65812222, 0.69149048, 0.97454363, 0.19451376,
        0.7002841 , 0.38344464, 0.38628287, 0.56396766, 0.72333138,
        0.78476713, 0.69621566, 0.65122844, 0.5552288 , 0.94699344,
        0.01995658, 0.17319269, 0.90724275, 0.8196212 , 0.13001383]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [104]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [82]:
new_array = np.array([x for x in range(12,26) if not x in (16,21)])
new_array = new_array.reshape(3,4)
new_array

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [84]:
new_array[1][-1]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [99]:
new_vertarray = new_array[:,0]-10
new_vertarray = new_vertarray.reshape(3,1)
new_vertarray

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [101]:
easy_array = np.arange(21,26)
easy_array

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [102]:
array_2d = np.arange(16,26).reshape(2,5)
array_2d

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [105]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [106]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [118]:
for column in range(mat.shape[1]):
    print(mat[:,column].sum())

55
60
65
70
75


# Great Job!